### ISSUE TITLE
Error on Line 6:29 - got value of type null

### ISSUE THREAD

**Issue by solbadguy2010** [olf/scriptable-netatmo-widget#2]
Hi, any idea what i am doing wrong?

![IMG_1181](https://user-images.githubusercontent.com/30244171/107875381-cce06900-6ebf-11eb-83ed-28ce227b3b2c.jpeg)

![IMG_1182](https://user-images.githubusercontent.com/30244171/107875383-cfdb5980-6ebf-11eb-92ae-aaac5805bdff.PNG)

<img width="802" alt="Bildschirmfoto 2021-02-14 um 12 26 28" src="https://user-images.githubusercontent.com/30244171/107875399-e2559300-6ebf-11eb-808a-416b47d48690.png">

<img width="454" alt="Bildschirmfoto 2021-02-14 um 12 24 40" src="https://user-images.githubusercontent.com/30244171/107875403-e681b080-6ebf-11eb-9c1e-6ff70c40166d.png">

**Comment by olf** [comment]
Looks like you have not specified the module name in the widget parameters, see screenshot in the readme file where it says "Indoor".
