### ISSUE TITLE
.config File not possible to copy

### ISSUE THREAD

**Issue by svenmarcelmueller** [olf/scriptable-netatmo-widget#3]
Hello together,

when I try to copy the "Netatmo.config" File to the icloud scriptable folder, I get the following Error Message: "Dieser Dateityp kann nicht in diesen App-Ordner hochgeladen werden." (This file type cannot be uploaded to this app folder).

Is there any workaround?

Thanks, Sven

**Comment by olf** [comment]
Sorry, I can't reproduce this on my Mac. Could you provide additional details on how you try to copy the file?

**Comment by svenmarcelmueller** [comment]
Here my steps:
- Download the zip with all the files
- unzip it with 7zip
- open Netatmo.config-template with Notepad++ and fill in my data
- save the file
- rename the file in the windows explorer to Netatmo.config
- Drag&Drop the file to the Browser where iCloud is open into the scriptable folder. Then I get the message as mentioned in my first post.
- Remark: renaimg Netatmo.conf to Netatmo.js can be copied

OS: Win 10
Browser: Chrome

**Comment by olf** [comment]
Oh, I see, iCloud Drive in the browser...

Here's a workaround that worked for me:

* upload the file(s) to a folder where you are allowed to upload them (or create a temporary folder in iCloud drive)
* then use the Files app on your iPhone or iPad to move the file(s) to the Scriptable folder

Hope this helps.

**Comment by olf** [comment]
@svenmarcelmueller Did this solve your issue, can we close this?

**Comment by svenmarcelmueller** [comment]
Sorry for the late answer, yes that works. You can close this. 
Many Thanks, Sven

**Comment by svenmarcelmueller** [comment]
Solved.
